__Submitted By:__
    
# Adil Sheraz
### PIAIC 143318 Batch-12
adil_2engr@hotmail.com

# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
vec_Z = np.arange(10,50)
print(vec_Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
vec_Z.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
print(type(vec_Z))

print(vec_Z.dtype)

<class 'numpy.ndarray'>
int32


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)

1.19.4


In [7]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [8]:
vec_Z.ndim

1

8. Create a boolean array with all the True values

In [9]:
bool_Array = np.array([10,11,12,13,14,15,'adil','sheraz'] , dtype = bool)
print(bool_Array)

[ True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [10]:
arr_2d = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

10. Create a three dimensional array



In [11]:
arr_3d = np.array([[[1,2,3,4,5],
                 [6,7,8,9,10],
                   [11,12,13,14,15]]])
arr_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
vec_Z = np.arange(10)
print(vec_Z)

vec_Z = vec_Z[::-1]
print(vec_Z)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
nul_Vec = np.zeros(10)
print(nul_Vec)
print()
nul_Vec[4] = 1
print(nul_Vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [14]:
iden_matrix = np.eye(3)
print(iden_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

# First method
float_arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(float_arr.dtype)

# Second method
float_arr1 = np.array([1, 2, 3, 4, 5.0])
print(float_arr1.dtype)

int32
float64
float64


15. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

print(arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

print(arr1 > arr2)

[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [18]:
a = np.arange(10)
print(a)
print()

# First Method
print(a[a % 2 != 0])

# Second Method
print(a[a % 2 == 1])

[0 1 2 3 4 5 6 7 8 9]

[1 3 5 7 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [19]:
a = np.arange(10)
print(a)
print()

a[a % 2 == 1] = -1

print(a)

[0 1 2 3 4 5 6 7 8 9]

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [20]:
arr = np.arange(10)
arr
print()
arr[5] = arr[6] = arr[7] = 12

print(arr)


[ 0  1  2  3  4 12 12 12  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [21]:
arr_2d = np.ones((10,10), dtype=int)
arr_2d
arr_2d[1:-1,1:-1] = 0
print(arr_2d)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

---

Replace the value 5 to 12

In [22]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# First Method
arr2d[1,1] = 12
arr2d

# Second Method
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print()
print("**************")
arr3d[:1,0:2] = 64
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

**************
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
array2d = np.arange(9).reshape(3,3)
print(array2d)
print("___________")
arr1d = array2d[0]
print(arr1d)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
___________
[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
array2d = np.arange(9).reshape(3,3)
print(array2d)
print("___________")
val_2nd = array2d[1][1]
print(val_2nd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
___________
4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
array2d = np.arange(9).reshape(3,3)
print(array2d)
print("___________")
col_3rd = array2d[:2,2:]
print(col_3rd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
___________
[[2]
 [5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
array = np.random.random((10,10))
print(array)

array_min, array_max = array.min(), array.max()
print("Array Min = ",array_min,"\n" ,"Array Max = ",array_max)

[[3.45744108e-01 7.45543338e-01 3.80706901e-01 7.89564993e-01
  9.73309788e-01 5.30850160e-01 1.68166064e-01 4.31355702e-01
  1.59082771e-01 5.32125634e-01]
 [1.55569259e-01 4.40197330e-02 2.39620003e-01 2.53630807e-01
  4.56647663e-01 5.49055199e-01 2.55580499e-01 2.61906965e-01
  5.10254551e-01 3.17478998e-01]
 [2.55994728e-01 2.57967226e-01 9.71560424e-01 4.30000371e-01
  8.31551083e-01 7.96186132e-02 6.64683101e-01 8.21027457e-01
  1.42267182e-01 7.35506411e-01]
 [3.27741041e-01 5.31524336e-02 8.09980558e-01 7.78270355e-01
  6.61020880e-01 1.71509935e-01 7.19441324e-01 1.07840468e-01
  9.08814705e-01 2.50467744e-01]
 [8.52594763e-01 7.65170352e-01 7.60249653e-01 9.53320977e-01
  3.30778503e-01 1.11177914e-01 9.33102961e-01 9.53413995e-01
  3.53176829e-01 6.55405420e-01]
 [6.95586668e-01 6.04745631e-01 4.35250803e-01 9.69430763e-02
  6.33226937e-01 3.74521734e-01 6.43156996e-01 3.46849143e-01
  5.35063023e-01 7.50642750e-01]
 [8.43575845e-01 3.88154187e-01 2.89508153e-01 4.78002250e

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Common items: ",np.intersect1d(a,b))

Common items:  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

# First Method
print(np.where(a==b))
print()

# Second Method
print(np.arange(len(a))[a==b])

(array([1, 3, 5, 7], dtype=int64),)

[1 3 5 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

# First Method
print(data[names != "Will"])
print()
# Second Method
print(data[~(names == "Will")])

[[ 0.3110746   0.3895577   0.49851262 -0.13437918]
 [ 1.04214214  0.52577842 -0.25536187  0.81838897]
 [-0.08277773  0.60715202 -0.95210722 -0.64280466]
 [ 0.44133332 -0.04646026 -0.08937591  0.8627116 ]
 [ 1.21796463  0.00705989  0.60262618  0.54543335]]

[[ 0.3110746   0.3895577   0.49851262 -0.13437918]
 [ 1.04214214  0.52577842 -0.25536187  0.81838897]
 [-0.08277773  0.60715202 -0.95210722 -0.64280466]
 [ 0.44133332 -0.04646026 -0.08937591  0.8627116 ]
 [ 1.21796463  0.00705989  0.60262618  0.54543335]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[ 1.2917747 ,  1.48792784,  0.41150686,  0.47770714],
       [-1.01033564,  1.7373273 , -0.59953648,  0.17930379],
       [-0.01579371, -0.6229241 , -0.61770154, -0.40770782],
       [ 0.2024949 , -0.84130919, -0.75853204, -0.94871242],
       [ 0.82669389, -1.47625739,  0.23417035, -1.15543437],
       [-1.94386704, -0.38121511, -0.36920939,  0.44302338],
       [-0.97172303,  1.25388884,  0.98094576,  0.76387455]])

In [32]:
names == "Will"

array([False, False,  True, False,  True, False, False])

In [33]:
names == "Joe"

array([False,  True, False, False, False,  True,  True])

In [34]:
mask = (names == "Will") | (names == "Joe")
print(names[~ mask])

['Bob' 'Bob']


In [35]:
data[~mask]

array([[ 1.2917747 ,  1.48792784,  0.41150686,  0.47770714],
       [ 0.2024949 , -0.84130919, -0.75853204, -0.94871242]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [36]:
arr_2d = np.arange(1,16).reshape(5,3)
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [37]:
x = np.arange(1,17).reshape(2,2,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [38]:
x.shape

(2, 2, 4)

33. Swap axes of the array you created in Question 32

In [39]:
print(x.T)

[[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]


In [40]:
print(np.transpose(x))

[[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]


In [41]:
print(x.T.shape)

(4, 2, 2)


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [42]:
arr_x = np.arange(10)
print(arr_x)
print()
print(np.sqrt(arr_x))

[0 1 2 3 4 5 6 7 8 9]

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [43]:
x = np.random.randn(12)
print('x = ',x )
print()
y = np.random.randn(12)
print('y = ',y)
print()
print('max(x,y) = ',np.maximum(x,y))

x =  [-1.78743219  0.91268082 -1.06984502  0.44478991  1.03561542 -1.06131754
  0.91258516  1.21150101  1.14383493  1.03959001  1.2494409   0.55116639]

y =  [ 1.06134596 -1.09720387  0.92326163 -1.40602114 -0.63847932  0.22810653
  0.86722628 -0.71058177  3.70264867  1.71010239  0.19929095  0.19407041]

max(x,y) =  [1.06134596 0.91268082 0.92326163 0.44478991 1.03561542 0.22810653
 0.91258516 1.21150101 3.70264867 1.71010239 1.2494409  0.55116639]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(np.sort(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [45]:
a = np.array([1,2,3,4,5])
print(a)
b = np.array([5,6,7,8,9])
print(b)
print()

a = np.setdiff1d(a,b)
print(a)


[1 2 3 4 5]
[5 6 7 8 9]

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [46]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [47]:
sampleArray[:,1:2] = 10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [48]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
print(x)
print()
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(y)

print()
print(np.dot(x,y))

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [49]:
zy = np.random.randn(20)
print(zy)

[-1.46655629 -0.12185095  1.05182643 -0.83917725 -1.17992195  0.38679059
  0.75076977 -0.23181729  0.60739892  0.13072728 -0.7189018  -1.95939463
 -1.74390855  0.70975784  1.21099107 -1.41312327 -0.60769305 -0.58308166
  1.19414369 -1.99545639]


In [50]:
# First Method
zy.cumsum()

array([-1.46655629, -1.58840724, -0.53658082, -1.37575807, -2.55568002,
       -2.16888943, -1.41811966, -1.64993695, -1.04253803, -0.91181075,
       -1.63071255, -3.59010718, -5.33401573, -4.62425789, -3.41326682,
       -4.82639009, -5.43408314, -6.01716479, -4.82302111, -6.8184775 ])

In [51]:
# Second Method
np.cumsum(zy)

array([-1.46655629, -1.58840724, -0.53658082, -1.37575807, -2.55568002,
       -2.16888943, -1.41811966, -1.64993695, -1.04253803, -0.91181075,
       -1.63071255, -3.59010718, -5.33401573, -4.62425789, -3.41326682,
       -4.82639009, -5.43408314, -6.01716479, -4.82302111, -6.8184775 ])