# Numpy_Assignment_2::

### Adil Sheraz
### PIAIC 143318

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr1 = np.arange(10)
print(arr1)
print()

arr2d = arr1.reshape(2,5)
arr2d

[0 1 2 3 4 5 6 7 8 9]



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [27]:
ar1 = np.arange(10).reshape(2,5)
print(ar1)

ar2 = np.ones(10,int).reshape(2,5)
print(ar2)
print()
ar_final = np.vstack([ar1,ar2])
ar_final

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [28]:
ar1 = np.arange(10).reshape(2,5)
print(ar1)

ar2 = np.ones(10,int).reshape(2,5)
print(ar2)
print()
ar_final = np.hstack([ar1,ar2])
ar_final

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]



array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [37]:
a = np.arange(10).reshape(2,5)
print(a)

b = a.flatten()
b

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [43]:
a = np.arange(15).reshape(5,3)
print(a)

b = a.flatten()
b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [46]:
a = np.arange(15)
print(a)

print()
b = a.reshape(5,3)
b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [50]:
a = np.arange(25).reshape(5,5)
print(a)
print()

print(np.square(a))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [53]:
a = np.arange(30).reshape(5,6)
print(a)
print()

a_mean = np.mean(a)
print("Mean of array: ",a_mean)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Mean of array:  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [54]:
a = np.arange(30).reshape(5,6)
print(a)
print()

a_std = np.std(a)
print("Standard Dev of array: ",a_std)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Standard Dev of array:  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [56]:
a = np.arange(30).reshape(5,6)
print(a)
print()

a_median = np.median(a)
print("Median of array: ",a_median)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Median of array:  14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [59]:
a = np.arange(30).reshape(5,6)
print(a)
print()

# First way
print(a.T)
print()

# Second way
print(np.transpose(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [65]:
a = np.arange(16).reshape(4,4)
print(a)
print()
print("Diagonal Sum: ",np.trace(a))
print("Diagonal Elements: ",np.diagonal(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Diagonal Sum:  30
Diagonal Elements:  [ 0  5 10 15]


## Question:13

### Find the determinant of the previous array in Q12?

In [77]:
from numpy.linalg import det
a = np.arange(16).reshape(4,4)
print(a)
print()

det(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
a = np.arange(500,700)
print(a)
print()
print("{0} - is the 5th percentile".format(round(np.percentile(a,5),2)))
print("{0} - is the 95th percentile".format(round(np.percentile(a,95),2)))

[500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517
 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535
 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553
 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571
 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589
 590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607
 608 609 610 611 612 613 614 615 616 617 618 619 620 621 622 623 624 625
 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643
 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661
 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676 677 678 679
 680 681 682 683 684 685 686 687 688 689 690 691 692 693 694 695 696 697
 698 699]

509.95 - is the 5th percentile
689.05 - is the 95th percentile


## Question:15

### How to find if a given array has any null values?

In [25]:
a = np.arange(5)
print(a)
print(np.isnan(a).any())

print()
b = np.array([40,np.nan,50])
print(b)
print(np.isnan(b).any())

[0 1 2 3 4]
False

[40. nan 50.]
True
